### ISSUE TITLE
TestCommand for ConfigStore

### ISSUE THREAD

**Issue by rannn505** [configu/configu#107]
**Description**

- We will add a new command to the sdk and the cli that verifies a certain store, meaning that its credentials are valid and that we can write to it.
- TestCommand({ store: ConfigStore }) class will be addend to the base ts SDK and the py SDK
- configu test --store "type" will be added to the CLI
- The command receives a store, initializes it, and try to `upsert` a default key named `CONFIGU_TEST` with a random value.
- the result of the Test will be a boolean of true or false
- [Bouns] The command will receive another boolean param named `clean`, and if passes the key will be deleted after the initial upset. 

**Motivation**

- Add the ability to create a "dev-first" bash script like this
```py
import subprocess


def run(command_line: str) -> str:
    proc = subprocess.Popen(command_line, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
    (out, err) = proc.communicate()

    if out:
        return out.decode('ascii').strip()
    if err:
        return err.decode('ascii').strip()
    return 'Error running command line'
    

if __name__ == '__main__':
    EXPORT_CMD = "configu export --from 'store=configu;set=dev/{username};schema=./env.cfgu.json'"

    if not run("configu --version").startswith('@configu'):
        print('Please install configu: https://configu.com/docs/cli-setup/#install-with-script')
    elif 'Error' in run(EXPORT_CMD): <---- THIS SHOULD BE REPLACED WITH THE TEST COMMAND
        print('Please login to Configu using: configu store upsert --type "configu"')
    else:
        run(f'{EXPORT_CMD} --template-input=array --template=./env.tmpl > ../.env2')
```

**Additional context**

**Comment by RonConfigu** [comment]
### General Strategy
 - Implement in TS SDK using existing store.set
 - Review CLI code structure and implement

### Questions / Clarifications
- random value - Date.now().toString() is my go-to. which is yours? @RichardAkman @rannn505
