### ISSUE TITLE
Fix key:value set() and remove wildcards from py

### ISSUE THREAD

**Issue by RonConfigu** [configu/configu#132]
**Description**

**Motivation**

**Additional context**

**Comment by RichardAkman** [comment]
Issues should only address one subject which isn't the case here. We have a bug to solve in the TS and PY SDK and we also have to remove the wildcards specifically in the PY SDK. Let's split this issue into two. 

- Rename this issue into something like `Fix and align key-value store set method`.
- Create a new issue `Remove config store query wildcards from py SDK`

Make sure to explain in the description of both issues what we're fixing and why in a concise way 🙏
