### ISSUE TITLE
Go SDK implementation!

### ISSUE THREAD

**Issue by jamesL92** [configu/configu#135]
**Description**
An initial go implementation of the SDK. Maybe only supporting in-memory/json/configu stores initially for simplicity.

**Motivation**
Golang is increasing in popularity, would be nice to support it. 
Also I wouldn't mind trying to come up with an initial implementation myself (for a bit of practice), just not sure if Configu is ready to support/maintain a go library yet - checking here first so that I'm not wasting my time :sweat_smile:

**Additional context**

**Comment by rannn505** [comment]
Dear @jamesL92,

Firstly, thank you for showing such interest in contributing to Configu. We highly appreciate your initiative and are excited about the idea of introducing a Go implementation of the SDK. Your suggestions and enthusiasm are valuable to the growth and expansion of the project.

In terms of readiness, Configu is indeed prepared to support and maintain a Go library. We believe in the adaptability and expansiveness of our project, and introducing a new language implementation would be a great step forward. The fact that GoLang is rising in popularity, as you've pointed out, makes it an excellent choice.

Your offer to contribute an initial implementation is more than welcome. Contributions like these are what make open-source projects like Configu thrive. For sure, it won't be a waste of your time.

I suggest we continue this conversation both here and through email/zoom meeting so we can dive deeper into the details of the SDK skeleton implementation and deployment process. Feel free to reach out to me at ran@configu.com. We are eager to support you on this journey.

Looking forward to our collaboration and once again, thank you for your willingness to contribute.

Best Regards,
Ran and the whole Configu team.

**Comment by rannn505** [comment]
@jamesL92  couple of resources I gathered as preparation for the implementation:

### `quicktype` npm script to the add to the package.json
```json
  scripts: {
    "prepare:go": "npm run types -- --lang go [--package configu ?] --out go/.../generated.go"
}
```
You can test the different outputs with all the specific go flags here: https://app.quicktype.io/#l=go
Also you can see the actual flags name running `npx quicktype --help` in the root this:
![image](https://github.com/configu/configu/assets/11806915/3f5447bb-69f4-43a4-bceb-dc3180447cae)

### equivalent dependencies to other SDKs
[ts deps](https://github.com/configu/configu/blob/main/ts/packages/ts/package.json#L33) | [py deps](https://github.com/configu/configu/blob/main/py/pyproject.toml#L31)

#### HTTP Client
- ts: [Axios](https://axios-http.com/docs/intro)
- pt: [Requests](https://requests.readthedocs.io/en/latest/) / should we change?
- go: [native](https://pkg.go.dev/net/http) / [resty](https://github.com/go-resty/resty) / other from https://awesome-go.com/http-clients/

#### String validation
- ts: [validator](https://github.com/validatorjs/validator.js)
- py: [py-validator](https://pypi.org/project/py.validator/) / should we change?
- go: [Package validator](https://github.com/go-playground/validator) / other from https://awesome-go.com/validation/

#### Templating
mustache main page - https://mustache.github.io/
- ts: [mustache](https://github.com/janl/mustache.js)
- py: [chevron](https://github.com/noahmorrison/chevron) / should we change? (I heard Jinja is great - I guess it should be compatible with `{{mustaches}}` curly brackets style)
- go: [mustache](https://github.com/cbroglie/mustache) / other from https://awesome-go.com/template-engines/

#### Linter
- ts: [eslint](https://eslint.org)
- py: [flake8](https://flake8.pycqa.org/en/latest/) / should we change?
- go: [golangci-lint](https://golangci-lint.run/) / other from https://awesome-go.com/code-analysis/

#### formatter
- ts: [prettier](https://prettier.io/)
- py: [black](https://pypi.org/project/black/) / should we change?
- go: [gofmt](https://go.dev/blog/gofmt) / other from https://awesome-go.com/formatters

#### Test runner
- ts: [jest](https://jestjs.io/)
- py: [pytest](https://docs.pytest.org/en/latest/) & pytest-cov / should we change?
- go: [native](https://pkg.go.dev/testing) / other from https://awesome-go.com/testing/

#### reference docs
- ts: [typedoc](https://typedoc.org)
- py: [pdoc](https://pdoc.dev/) / should we change?
- go: [godoc](https://pkg.go.dev/golang.org/x/tools/cmd/godoc) / other ?

### GitHub actions for `cd-go.yml` and `go-env-action/action.yml`

- https://github.com/marketplace/actions/setup-go-environment
- https://goreleaser.com/

I would appreciate your help in choosing the dependencies and introducing new resources that you think will help.

**Comment by jamesL92** [comment]
Thanks @rannn505, those resources are incredibly helpful :+1: 

Where possible I'd like to stick to native packages as much as possible, makes maintaining the code much easier. I'll take a look through some of the above SDKs to see which ones fit best for my golang implementation :)
