### ISSUE TITLE
Implement `DateTime` `Cfgu Type`

### ISSUE THREAD

**Issue by rannn505** [configu/configu#139]
**Description**

Add a `DateTime` type (`YYYY/MM/DD`, `YYYY-MM-DD` etc.) to the Cfgu type system of Configu.
It could also potentially be 2 different types (Date, Time).

Using `type: Date` and optionally `format: YYYY/MM/DD` in a ConfigSchema should enforce a `valid date time` with or without a `strict format` as a config value at `upsert` or `eval`.
```json
{
  ...
  "CONFIG_KEY": {
    "type": "DateTime",
    "format": "YYYY/MM/DD"
  }
  ...
} 
```

**Motivation**

Extending Configu's type system capabilities.

**Additional context**

- https://github.com/validatorjs/validator.js
- https://day.js.org/docs/en/parse/is-valid
- https://day.js.org/docs/en/parse/string-format
- https://learn.microsoft.com/en-us/system-center/orchestrator/standard-activities/format-date-time?view=sc-orch-2022
- https://configu.com/docs/cfgu/
- https://github.com/configu/configu/blob/main/types/Cfgu.ts

**Comment by jamesL92** [comment]
Could potentially support 3 separate Cfgu types here - `date`, `time` and `datetime`

**Comment by rannn505** [comment]
@jamesL92 totally agree.
