### ISSUE TITLE
Implement `CreditCard` `Cfgu Type`

### ISSUE THREAD

**Issue by rannn505** [configu/configu#142]
**Description**

Add a `CreditCard` type to the Cfgu type system of Configu.

Using `type: CreditCard` in a ConfigSchema should enforce a valid Credit Card number (amex, visa, mastercard, etc..) as a config value at `upsert` or `eval`.
```json
{
  ...
  "CONFIG_KEY": {
    "type": "CreditCard"
  }
  ...
} 
```

**Motivation**

Extending Configu's type system capabilities.

**Additional context**

- https://github.com/validatorjs/validator.js
- https://configu.com/docs/cfgu/
- https://github.com/configu/configu/blob/main/types/Cfgu.ts
- https://en.wikipedia.org/wiki/Credit_card

**Comment by jamesL92** [comment]
May be something you've already considered but I'd recommend a bit of caution with this one, particularly w.r.t. supporting this in the `ConifguConfigStore`.

While users could _technically_ already store credit card numbers in Configu via `CfguType.STRING`, explicitly supporting credit card number configs means you'll need to be extra careful around how you support/store this information in `Configu` for compliance reasons - see [here](https://www.globalpaymentsintegrated.com/en-us/blog/2019/11/25/pci-rules-for-storing-credit-card-numbers-in-a-database) for example.

It _may_ be something you've already considered, but I thought it might be worth pointing out just in case.

**Comment by rannn505** [comment]
@jamesL92 you raise an important point. While the `ConifguConfigStore` does support encryption on multiple levels, adding a specific CreditCard type would certainly shine a spotlight on data sensitivity and compliance considerations.

Indeed, this new type is essentially just a schema feature that applies validation on the final value, and users have the flexibility to decide which ConfigStore they use. Nonetheless, your cautionary note is well taken - such a feature might raise concerns, even if the actual implications are more benign.

Given these considerations, let's agree to deprioritize this feature for now, until someone decides to implement it with full awareness of the potential concerns and complexities involved.

**Comment by IAmRiteshKoushik** [comment]
Has this issue been resolved already or is it still being worked upon ?

**Comment by rannn505** [comment]
@IAmRiteshKoushik, thank you for your interest in this issue! While there has been some progress by @bharathgaddam1712 ([see PR #263](https://github.com/configu/configu/pull/263)), it is currently still a Work in Progress. You're welcome to review the ongoing discussion within that pull request and perhaps collaborate with @bharathgaddam1712 on its completion. Your contributions would be greatly appreciated!

**Comment by SanchitMahajan236** [comment]
If this issue is open for contribution, I would love to contribute to this issue. Can you please assign me this issue ?

**Comment by rannn505** [comment]
@SanchitMahajan236 It’s all yours! 😊

**Comment by SanchitMahajan236** [comment]
@rannn505 please check my PR #481
