### ISSUE TITLE
Implement `Language` `Cfgu Type`

### ISSUE THREAD

**Issue by rannn505** [configu/configu#143]
**Description**

Add a `Language` type to the Cfgu type system of Configu.

Using `type: Language` in a ConfigSchema should enforce a two-letter language code as a config value at `upsert` or `eval`.
```json
{
  ...
  "CONFIG_KEY": {
    "type": "Language"
  }
  ...
} 
```

**Motivation**

Extending Configu's type system capabilities.

**Additional context**

- https://github.com/validatorjs/validator.js
- https://configu.com/docs/cfgu/
- https://github.com/configu/configu/blob/main/types/Cfgu.ts
- https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by RonConfigu** [comment]
This is misleading in my opinion.
`Language` doesn't suggest `ISO639-1` necessarily. `English` is a language and this will break here.
