### ISSUE TITLE
Implement `Unleash` `ConfigStore` in Node.js SDK

### ISSUE THREAD

**Issue by rannn505** [configu/configu#149]
**Description**

- Plan a `Config` read with `isEnabled` and context.
- This Store might be a `read-only`. Setting the actual FeatureFlag will be made via the Unleash UI.
- Add `UnleashConfigStore` class to the Node.js SDK stores.
- We can use the official Unleash [Node.js SDK](https://github.com/Unleash/unleash-client-node)

**Motivation**

Extending Configu's [available stores](https://configu.com/docs/config-store/#available-stores) collection.
This ConfigStore will be made available in the Configu CLI since the Node.js SDK is used internally.

**Additional context**

- https://www.getunleash.io/
- https://docs.getunleash.io/reference/sdks/node
- https://configu.com/docs/config-store/
- https://github.com/configu/configu/blob/main/types/ConfigStore.ts
- https://github.com/configu/configu/tree/main/ts/packages/node/src/stores

![image](https://github.com/configu/configu/assets/11806915/e603c3c3-703c-46d2-91a6-3c308089a8ce)

**Comment by Anurag-space** [comment]
Thanks for assigning me this issue.

**Comment by rannn505** [comment]
@Anurag-space any progress? do you need help?

**Comment by RichardAkman** [comment]
@Anurag-space 

We've noticed that this issue has been inactive for some time, and we'd like to keep the project's progress moving forward. Since we haven't seen any recent activity from you on this issue, we'll be unassigning it for now.

Thanks for your understanding and for your involvement in our community!
