### ISSUE TITLE
Implement `SplitConfigStore` in `@configu/integrations`

### ISSUE THREAD

**Issue by rannn505** [configu/configu#150]
### Suggestion

- Plan a `Config` read with `getTreatment ` and attributes.
- This Store might be a `read-only`. Setting the actual FeatureFlag will be made via the Split UI.
- Add `SplitConfigStore` class to @configu/integrations package.
- We can use the OpenFeature BaseStore with https://github.com/splitio/split-openfeature-provider-js

### Motivation

Extending Configu's [available stores](https://configu.com/docs/config-store/#available-stores) collection.
This ConfigStore will be made available in all Configu interfaces such as the Configu CLI with the remoteRegister API.

### Context

- https://www.split.io/
- https://help.split.io/hc/en-us/articles/360020564931-Node-js-SDK
- https://configu.com/docs/config-store/
- https://github.com/configu/configu/blob/main/packages/sdk/src/core/ConfigStore.ts
- https://github.com/configu/configu/tree/main/packages/integrations/stores

![Configu OSS Flow Diagram](https://github.com/user-attachments/assets/5930d73b-8b5b-4068-a5dc-e3cb073ad27b)

**Comment by akshay11298** [comment]
Hi @rannn505 , Can you please assign this issue to me? I have raised a PR for this as well with a probable solution
