### ISSUE TITLE
Implement `CSV` `ConfigStore` in Node.js SDK

### ISSUE THREAD

**Issue by rannn505** [configu/configu#151]
**Description**

- Plan a `Config` accommodation in the csv file.
- Add `CSVConfigStore` class to the Node.js SDK stores.
- A quick search indicates that [csv](https://www.npmjs.com/package/csv) library or [xlsx](https://www.npmjs.com/package/xlsx) are the most "suitable" for use during implementation.
- We would be happy to hear more suggestions, or we can implement the APIs ourselves.

**Motivation**

Extending Configu's [available stores](https://configu.com/docs/config-store/#available-stores) collection.
This ConfigStore will be made available in the Configu CLI since the Node.js SDK is used internally.

**Additional context**

- https://en.wikipedia.org/wiki/Comma-separated_values
- https://configu.com/docs/config-store/
- https://github.com/configu/configu/blob/main/types/ConfigStore.ts
- https://github.com/configu/configu/tree/main/ts/packages/node/src/stores

![image](https://github.com/configu/configu/assets/11806915/e603c3c3-703c-46d2-91a6-3c308089a8ce)

**Comment by jamesL92** [comment]
Rather than a new ConfigStore, what about generalising the existing [JsonFileConfigStore](https://github.com/configu/configu/blob/main/ts/packages/node/src/stores/JsonFile.ts#L7) to a more general `FileConfigStore` that accepts a `fileFormat` initialisation parameter?

An alternative route would be to abstract a `FileConfigStore` out of the `JsonFileConfigStore`, similar to what's done with [KeyValueConfigStore](https://github.com/configu/configu/blob/main/ts/packages/ts/src/stores/KeyValue.ts#L5)

**Comment by rannn505** [comment]
@jamesL92 You've got a good point there. While the idea of a fileFormat option in the constructor sounds appealing for its generality, it may indeed lead to a bloated class due to the need to handle different formats within the same class.

With that in mind, your suggestion of an abstract FileConfigStore class is particularly attractive. This would allow us to maintain a lean, clean class while still achieving the flexibility we desire.

Let's move in this direction, and as always, thanks for your valuable insights!

**Comment by cstayyab** [comment]
@rannn505 What if instead of using `FileConfigStore`  as base class we use  `JsonFileConfigStore` as base since a lot of formats can be easily represented into JSON including but not limited to `CSV`(this issue), `yaml`, `ini` (#152) and many others.

**Comment by rannn505** [comment]
@cstayyab I see where you're coming from, and your point makes sense from a structural perspective. However, I believe users would prefer to interact with the specific file format they've chosen. For instance, if someone opts for CSVStore, they'd likely expect Configu to read from and write to an actual CSV file in their project.

**Comment by vibh1103** [comment]
Hi @rannn505 @cstayyab 
can i pick this task ?

**Comment by rannn505** [comment]
@vibh1103, it's all yours, buddy! Looking forward to seeing your contributions.

**Comment by RichardAkman** [comment]
Hi @vibh1103, Sadaf is currently unavailable to continue work on his PR. Do you want to pick up where he left off?

**Comment by vibh1103** [comment]
Hi @RichardAkman  you can pick this task i don't have to work on it. @rannn505 please assign this task to @RichardAkman. Sorry for inconvenience.
