### ISSUE TITLE
Is json-file enabled to use? I had TypeError: JsonFileStore is not a constructor

### ISSUE THREAD

**Issue by FMGordillo** [configu/configu#153]
**Actual behavior**

Tried to replicate [this example](https://github.com/configu/configu/tree/main/examples/js-sdk) but it's giving me an error from the library

**To Reproduce**
<!-- Steps to reproduce the behavior:
1. Get example file: https://github.com/configu/configu/tree/main/examples/js-sdk
2. Install dependency (current version 0.14.0)
4. Run `node index.js`

**Expected behavior**
Expected to read json file locally and operate with it

**Screenshots**
```
/home/fmgordillo/code/configuration/index.js:7
  const store = new JsonFileStore(path.resolve(__dirname, './store.json'));
                ^

TypeError: JsonFileStore is not a constructor
    at /home/fmgordillo/code/configuration/index.js:7:17
    at Object.<anonymous> (/home/fmgordillo/code/configuration/index.js:19:3)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

**Additional context**
N/A

**Comment by jamesL92** [comment]
Can confirm I'm seeing the same thing. @FMGordillo it appears the examples are somewhat out-of-date - `JsonFileStore` was renamed `JsonFileConfigStore` in v12.0.0. Changing this in the example code fixes the bug.

Should be a quick fix to the examples, I'll pick this up :slightly_smiling_face:

**Comment by rannn505** [comment]
Hi @FMGordillo,

Firstly, thank you for raising this issue. @jamesL92 hit the nail on the head - the change from v12 wasn't reflected in our example directories.

Thank you for the quick solution, @jamesL92. We'll merge it as quickly as possible.

As part of ongoing efforts to improve Configu, I plan to review and update all our examples, as well as add some new ones in the upcoming week, so stay tuned!

Once you've managed to implement Configu in your project, @FMGordillo, we would really appreciate hearing your feedback. If you have a cool usage scenario you'd like to share, we'd be more than happy if you could contribute an example to our collection.
