### ISSUE TITLE
Implement `DockerImage` `Cfgu Type`

### ISSUE THREAD

**Issue by rannn505** [configu/configu#161]
**Description**

Add a `DockerImage` type to the Cfgu type system of Configu.

Using `type: DockerImage` in a ConfigSchema should enforce a Docker Image NAME[:TAG|@DIGEST] as a config value at `upsert` or `eval`.
Example of a DockerImage:
- image/tag:v1.0.0
- 123.123.123.123:123/image/tag:v1.0.0
- your-domain.com/image/tag
-  your-domain.com/image/tag:v1.1.1-patch1
-  image/tag
-  image
-  image:v1.1.1-patch
-  ubuntu@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2
```json
{
  ...
  "CONFIG_KEY": {
    "type": "DockerImage"
  }
  ...
} 
```

**Motivation**

Extending Configu's type system capabilities.

**Additional context**

- https://stackoverflow.com/questions/39671641/regex-to-parse-docker-tag
- https://configu.com/docs/cfgu/
- https://github.com/configu/configu/blob/main/types/Cfgu.ts
- https://www.docker.com/

**Comment by Sadaf-A** [comment]
Greetings! @rannn505 I would like to pick this up

**Comment by rannn505** [comment]
Hey @Sadaf-A,

Fantastic, I'm thrilled to hear that you're interested in taking this on!

To get started, please follow these steps:
1. Fork the repository
2. Create your feature branch (git checkout -b feature/dockerImageType)
3. Commit your changes (git commit -am 'Add DockerImage Type')
4. Push to the branch (git push origin feature/dockerImageType)
5. Open a Pull Request

If you have any questions or need further clarification at any point, please don't hesitate to ask. I'm here to help!

I look forward to reviewing your pull request.

Best,
Ran

**Comment by Sadaf-A** [comment]
Hi, @rannn505 
I've made the desired changes and pushed the code to the feature branch
I wanted to run tests with the examples that you have provided
I'm not able to setup a test environment could you please direct me to a resource which provides help regarding same

**Comment by Sadaf-A** [comment]
Hey, @rannn505 
I have opened a PR please have a look.
