### ISSUE TITLE
EvalCommad overrides should/n't override configs from other schemas?

### ISSUE THREAD

**Issue by RonConfigu** [configu/configu#171]
Notice on data3 EvalCommand, even though i'm passing configs overrides for `GREETING` it doesn't override it. this is because this key is from the previous and current schema. is this intended? 
![image](https://github.com/configu/configu/assets/129258356/893a1b42-93aa-4282-bdea-e8c4bb864fa1)

![image](https://github.com/configu/configu/assets/129258356/c966626f-bad9-4c0b-8ff7-75e9d6e20fbc)

**Comment by rannn505** [comment]
This issue has been resolved with the recent release
The fix has been tested and confirmed to be working as expected.
If you encounter any further issues or have additional questions, please feel free to open a new issue or comment on this thread.
