### ISSUE TITLE
Use `import type` instead of `import` while importing types

### ISSUE THREAD

**Issue by Sadaf-A** [configu/configu#207]
**Description**

The `import type` syntax in TypeScript is used to import only the types from a module, rather than the entire module. This can be useful for a few reasons:

- It can help to improve performance. When you import a module using `import`, TypeScript has to compile the entire module, even if you only need a few of the types. Using `import type` can help to reduce the amount of code that TypeScript has to compile, which can improve performance.

- It can help to improve readability. When you import a module using `import`, you have to import all of the types, even if you only need a few of them. This can make your code more difficult to read and maintain. Using `import type` can help to make your code more readable by only importing the types that you need.

- it can help to improve type safety. When you import a module using `import`, TypeScript only checks the types of the values that you use from the module. This can lead to type errors if you try to use a value from the module in a way that is not allowed by its type. Using `import type` can help to improve type safety by checking the types of all of the declarations in the module, even if you don't use them.

**Motivation**
Improve type checking for `configu`.

**Additional context**
https://stackoverflow.com/questions/50441093/is-there-a-point-to-doing-import-type-rather-than-import-with-flow#:~:text=Importing%20only%20the%20type%20can,new%20instance%20of%20that%20class.

**Comment by DarhkVoyd** [comment]
@Sadaf-A I'm eager to help with this, so please let me know how I can get started. Thanks!

**Comment by Sadaf-A** [comment]
@DarhkVoyd That is great to hear, you may replace every instance where we are using `import` with `import type` in a situation where we are only importing a type. This may have many benefits as described in the original issue. https://github.com/configu/configu/blob/main/CONTRIBUTING.md please go through this doc once before starting. you may join the discord server and ask any queries that may arise. Thank you for deciding to contribute!

**Comment by DarhkVoyd** [comment]
@Sadaf-A Sure, you can assign this to me. I am starting to work on this.

**Comment by DarhkVoyd** [comment]
@RichardAkman Hey, thanks for assigning this issue to me but I already resolved it and created the above PR.
