### ISSUE TITLE
CfguType(ConnectionString) RegEx is too broad

### ISSUE THREAD

**Issue by RonConfigu** [configu/configu#233]
**Actual behavior**
Couldn't find any string that doesn't match the RegEx.
for example:
`://example.com`
should not match

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by rannn505** [comment]
We decided to drop this `type` for now, thanks

**Comment by rannn505** [comment]
We decided to drop this `type` for now, thanks
