### ISSUE TITLE
Implement `Amazon Resource Names (ARNs)` `Cfgu Type`

### ISSUE THREAD

**Issue by rannn505** [configu/configu#235]
**Description**

Add a `ARN` type to the Cfgu type system of Configu.

Using `type: ARN` in a ConfigSchema should enforce a valid ARN as a config value at `upsert` or `eval`.

ARN format:
```
arn:partition:service:region:account-id:resource-id
arn:partition:service:region:account-id:resource-type/resource-id
arn:partition:service:region:account-id:resource-type:resource-id
```

```json
{
  ...
  "CONFIG_KEY": {
    "type": "ARN"
  }
  ...
} 
```

**Motivation**

Extending Configu's type system capabilities.

**Additional context**

- https://docs.aws.amazon.com/IAM/latest/UserGuide/reference-arns.html
- https://configu.com/docs/cfgu/
- https://github.com/configu/configu/blob/main/types/Cfgu.ts

**Comment by AceAbhi147** [comment]
Hey @rannn505 ..
Please review this: https://github.com/configu/configu/pull/245.
Here is the regex that I used and some string for testing: https://regexr.com/7jcm4

Let me know if I missed anything.

**Comment by rannn505** [comment]
Certainly @AceAbhi147, I'll review PR #245 and the associated regex shortly. I appreciate the test strings you've provided; they'll definitely help in the evaluation. I'll let you know if anything seems amiss. Thanks for your contribution!

Also, please merge `main` to your current branch so the diff will be shorter and focus only for the ARN type as the MongoId type is already merged :)

**Comment by AceAbhi147** [comment]
@rannn505.. sure thing.
Also, I did merge the main into my branch before making my changes.
This PR has one small change for MongoId. I didn't add validation for it in golang file in my last PR.
That change is also part of this PR.
