### ISSUE TITLE
Implement `options` Property for Cfgu Declaration

### ISSUE THREAD

**Issue by rannn505** [configu/configu#240]
**Description**
Introduce an `options` property to the Cfgu declaration. Represented as an array of strings, this property would restrict the value to be one from a predefined set. Specifying `options: ['X', 'Y', 'Z']` would be equivalent to using `type: "RegEx"` alongside `pattern: "^(X|Y|Z)$"`.

```json
{
  ...
  "CONFIG_KEY": {
    "type": "String",
    "options": ["X", "Y", "Z"]
  }
  ...
} 
```

**Motivation**
The aim is to bolster the flexibility and user-friendliness of the Cfgu declaration by introducing intuitive alternatives to using the `RegEx` and `pattern` properties.

**Additional context**

**Comment by jamesL92** [comment]
Please assign this one to me. :+1: 

A couple of thoughts I've had around validation options here:
- Eval/Upsert commands should naturally check that the evaluated/upserted value should be in the schema `options`, if present.
- ConfigSchema parsing should have a couple of additional validation rules when `options` is present:
  - `options` shouldn't be an empty list
  - each option should be valid based on the type, e.g. a `Number` type can't have `foo` as its option.
  - if `default` is also present, the default value should be present in options.
  - `template` should not be present.

Please let me know if the above validation suggestions make sense, if there are any that should be changed/remove or if there are any additional validation rules that should be added.

**Comment by rannn505** [comment]
@jamesL92, it's all yours! It really seems like you've thought of everything. Go ahead – I'm looking forward to it. :)

**Comment by jamesL92** [comment]
One extra thing I just thought of - the options list shouldn't contain an empty string :sweat_smile:

**Comment by rannn505** [comment]
@jamesL92, while you're working on it, if you come across any missing validations on other properties, such as 'depends' which is also a string array, please let me know. I'll create a bug for it. Thanks! :)
