### ISSUE TITLE
No matching tag found in readme badge 

### ISSUE THREAD

**Issue by manzil-infinity180** [configu/configu#264]
![Screenshot_20230930-145918](https://github.com/configu/configu/assets/119070053/51b94320-1fd3-418f-961c-58693db3b468)
**Actual behavior**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by aditya-2010** [comment]
The version for Go interface package is v0.0.0-20230907113344-a10012777ad3.

Is this what is expected? If yes, could you assign this to me. I would like to PR.

![image](https://github.com/configu/configu/assets/57087973/9bd8a682-d1c4-4414-9601-8acfd0fe87fc)

**Comment by rannn505** [comment]
Dear @manzil-infinity180,
Thank you for your update. :)
We are on track to release a versioned tag tomorrow. The precise version number, i.e., 0.1.0, will be confirmed and shared then.

Cc: @jamesL92

**Comment by rannn505** [comment]
Close as the Python and Go SDKs are now archived and deprecated.
