### ISSUE TITLE
Add Discord Channel Link in Readme FILE

### ISSUE THREAD

**Issue by manzil-infinity180** [configu/configu#267]
**Description**

**Motivation**

**Additional context**

**Comment by manzil-infinity180** [comment]
@pelegpor

**Comment by manzil-infinity180** [comment]
@RichardAkman

**Comment by RichardAkman** [comment]
Hi @manzil-infinity180, we do have a link to our discord in our readme file under our contributing section:
![image](https://github.com/configu/configu/assets/47181182/6d51cda0-402b-4e0e-9b2c-2be7f0ece5b4)

Is that what you were referring to?

**Comment by manzil-infinity180** [comment]
> Hi @manzil-infinity180, we do have a link to our discord in our readme file under our contributing section: ![image](https://user-images.githubusercontent.com/47181182/272185993-6d51cda0-402b-4e0e-9b2c-2be7f0ece5b4.png)
> 
> Is that what you were referring to?

i think we should add badge for discord channel like 

> Hi @manzil-infinity180, we do have a link to our discord in our readme file under our contributing section: ![image](https://user-images.githubusercontent.com/47181182/272185993-6d51cda0-402b-4e0e-9b2c-2be7f0ece5b4.png)
> 
> Is that what you were referring to?

@RichardAkman how this looks (it attract more than the previous one) or it can be on the top 
<img width="1467" alt="Screenshot 2023-10-03 at 3 27 16 PM" src="https://github.com/configu/configu/assets/119070053/5467d310-bc1e-4a23-a4c6-bf236405d953">

**Comment by Sadaf-A** [comment]
> > Hi @manzil-infinity180, we do have a link to our discord in our readme file under our contributing section: ![image](https://user-images.githubusercontent.com/47181182/272185993-6d51cda0-402b-4e0e-9b2c-2be7f0ece5b4.png)
> > 
> > Is that what you were referring to?
> 
> i think we should add badge for discord channel like 
> 
> > Hi @manzil-infinity180, we do have a link to our discord in our readme file under our contributing section: ![image](https://user-images.githubusercontent.com/47181182/272185993-6d51cda0-402b-4e0e-9b2c-2be7f0ece5b4.png)
> > 
> > Is that what you were referring to?
> 
> @RichardAkman how this looks (it attract more than the previous one) or it can be on the top 
> <img width="1467" alt="Screenshot 2023-10-03 at 3 27 16 PM" src="https://github.com/configu/configu/assets/119070053/5467d310-bc1e-4a23-a4c6-bf236405d953">
> 
> 
> 

I don't think we should add it here as it looks uneven in the bullet points. adding it on the bottom or top may be a good idea as people may not go through the doc word to word they might miss the discord channel link. Adding an icon is a good idea

**Comment by RichardAkman** [comment]
@Sadaf-A @manzil-infinity180 you both provide valid points. @rannn505 please provide input.

**Comment by manzil-infinity180** [comment]
> Hi, We can add it here along with 2 or 3 more insightful badges. <img alt="image" width="911" src="https://user-images.githubusercontent.com/11806915/274201155-8dd5e279-07c1-430b-9337-1d327b88d9a6.png">
> 
> Here is the tag :) [![Discord](https://camo.githubusercontent.com/8e0b7e14641436e9489b6a5e85dedb96316a081145fb24e1427191e4166c1031/68747470733a2f2f696d672e736869656c64732e696f2f646973636f72642f3931393635393734363030333431303934343f636f6c6f723d353836354632266c6162656c3d446973636f7264266c6f676f3d646973636f7264266c6f676f436f6c6f723d7768697465)](https://discord.gg/cjSBxnB9z8)
> 
> @manzil-infinity180 would you like to open a PR?

Assign it to me

**Comment by manzil-infinity180** [comment]
Image-1
<img width="1420" alt="Screenshot 2023-10-12 at 8 08 07 PM" src="https://github.com/configu/configu/assets/119070053/effc53ce-46bf-42db-8d65-fad05e209ee3">

Image-2
<img width="1420" alt="Screenshot 2023-10-12 at 8 07 30 PM" src="https://github.com/configu/configu/assets/119070053/5d8c42a5-1b9c-4aef-a75d-746035e17150">

@RichardAkman which one looks good or any other thing should i add or change in it
