### ISSUE TITLE
Implement TOML ConfigStore in Node.js SDK

### ISSUE THREAD

**Issue by pelegpor** [configu/configu#268]
### Description

- Plan a Config accommodation in the TOML format.
- Add `TOMLConfigStore` class to the Node.js SDK stores.
- Consider using the `@iarna/toml` library or similar for parsing and stringifying TOML during implementation.
- We're open to other library suggestions or, if preferred, we can implement the APIs ourselves.

### Motivation

To extend Configu's available stores collection and support the TOML format, which is a popular configuration format. This ConfigStore will be integrated into the Configu CLI as the Node.js SDK is utilized internally.

### Additional context

- [TOML - Official GitHub Repository](https://github.com/toml-lang/toml)
- [Configu Config Store Documentation](https://configu.com/docs/config-store/)
- [ConfigStore TypeScript Definition](https://github.com/configu/configu/blob/main/types/ConfigStore.ts)
- [Configu Node.js SDK Stores](https://github.com/configu/configu/tree/main/ts/packages/node/src/stores)

![image](https://github.com/configu/configu/assets/50705727/6be4950c-20c8-45b6-ab6d-a88784f05f96)

**Comment by rannn505** [comment]
@cc @Sadaf-A

**Comment by RichardAkman** [comment]
Hi @Dev-Arhaan, thanks for your interest in contributing! Currently, @Sadaf-A is working on this, and he has opened a PR for it. If you're still interested in helping, you might want to reach out to Sadaf and see if there are any opportunities for collaboration. Your enthusiasm is much appreciated!

**Comment by Sadaf-A** [comment]
> Is anyone assigned to this task? If not I would like to work on it

@Dev-Arhaan Hey, it's great to see that you want to contribute. You can join our discord server and ping me. If you are up for it we can co-author the PR to get the job done faster.

**Comment by RichardAkman** [comment]
Hi @Dev-Arhaan, Sadaf is currently unavailable to continue work on his PR. Let me know if you want to take it up and I'll assign you the issue.

**Comment by Maran1947** [comment]
Hi, can i tackle this issue?

**Comment by Dev-Arhaan** [comment]
Hey Richard, I Saw this very late, I'd love to work on it, let me hop on discord and try to understand the problem
