### ISSUE TITLE
Implement XML ConfigStore in Node.js SDK

### ISSUE THREAD

**Issue by pelegpor** [configu/configu#269]
### Description

- Plan a Config accommodation in the XML format.
- Add `XMLConfigStore` class to the Node.js SDK stores.
- Consider using the `xml2js` library or similar for parsing and converting XML during implementation.
- We're open to other library suggestions or, if preferred, we can implement the APIs ourselves.

### Motivation

To extend Configu's available stores collection and support the XML format, which is a widely used configuration format. This ConfigStore will be integrated into the Configu CLI as the Node.js SDK is utilized internally.

### Additional context

- [XML on Wikipedia](https://en.wikipedia.org/wiki/XML)
- [Configu Config Store Documentation](https://configu.com/docs/config-store/)
- [ConfigStore TypeScript Definition](https://github.com/configu/configu/blob/main/types/ConfigStore.ts)
- [Configu Node.js SDK Stores](https://github.com/configu/configu/tree/main/ts/packages/node/src/stores)

![image](https://github.com/configu/configu/assets/50705727/2abc0db3-1619-4c3d-9c12-32cdea665775)

**Comment by Suraj-kumar00** [comment]
Hi @pelegpor, How are you doing?
My name is Suraj, Can I work on this Issue? Please assign it to me so I can start working on this Issue!!!

**Comment by pelegpor** [comment]
Hello @Suraj-kumar00,

I'm doing well, thank you for asking!

Of course, we'd greatly appreciate your contribution. I've assigned the issue to you. Feel free to start working on it and let us know if you have any questions or need further guidance.

Thank you for your initiative and dedication to the project!

Warm regards,
Peleg

**Comment by Suraj-kumar00** [comment]
Thank you @pelegpor, for assigning this issue to me, and I'll surely ask you when I get stuck anywhere, One thing I want to ask you here is whether I should create a draft pull request for the conversation, guidance or any other changes regarding this issue or just do these things here only?

**Comment by RichardAkman** [comment]
> Thank you @pelegpor, for assigning this issue to me, and I'll surely ask you when I get stuck anywhere, One thing I want to ask you here is whether I should create a draft pull request for the conversation, guidance or any other changes regarding this issue or just do these things here only? And can I know much time I have to solve this issue?

Hi @Suraj-kumar00, we're excited to see you take on this issue! Regarding your question, if you need any guidance or have any questions you can feel free to ask here in this issue or use our [Discord](https://discord.com/invite/cjSBxnB9z8) to bring the question to the rest of our wonderful and helpful community. Once you think your code is ready for review, feel free to submit it as a PR for our review.

**Comment by RichardAkman** [comment]
Hi @Suraj-kumar00 

I hope you're doing well. It's been almost two weeks since the issue was assigned to you, and we haven't seen any progress or a pull request from your side yet.

We truly appreciate your commitment and contributions to the project, but we also want to make sure that other contributors have a fair opportunity to participate. In the spirit of collaboration and ensuring a balanced workload, we decided to kindly unassign you from this issue.

This doesn't mean that you can't continue working on it or that you're not welcome to contribute in the future. We encourage your continued involvement in the project. However, this will allow others to step in and make progress on this particular issue.

If you have any questions, or concerns, or need assistance, please feel free to reach out to us. We're here to help and support one another in making this project a success.

Thank you for your understanding, and we look forward to your ongoing contributions to the project on other tasks or issues.

**Comment by Suraj-kumar00** [comment]
Sorry for not updating on this issue but I'm working, actually I'm college student so managing lot's of stuff but I'll try to let you soon what the update and if I face any doubt and problem I'll let you know.

**Comment by Maran1947** [comment]
I have successfully set up the project on my local machine. If this issue is still open, could you please assign it to me?

**Comment by Maran1947** [comment]
@RichardAkman Thank you for assigning me on this issue. Can you please provide some resources to run an existing store?

**Comment by Maran1947** [comment]
I have a question regarding implementation: Should I extend **ConfigStore**/**FileConfigStore** in **XMLConfigStore** or implement it directly with parse and stringify methods? I would greatly appreciate any guidance on this matter. Thank you!

**Comment by RichardAkman** [comment]
@Maran1947 Great question, you should extend `FileConfigStore` as it wraps all file storage logic in useful logic such as creating the file in case it does not exist during upsert. I'll make sure to write a follow-up comment with some resources as you asked soon. Let me know if you have any further questions, you can even feel free to visit our [community Discord](https://discord.com/invite/cjSBxnB9z8) to get input from members of the community.

**Comment by RichardAkman** [comment]
@Maran1947 have you managed to get a store running?

**Comment by Maran1947** [comment]
> @Maran1947 have you managed to get a store running?

Not yet, I need help with this.

**Comment by RichardAkman** [comment]
@Maran1947, following up with you.

I recommend starting by following the [Node.js SDK docs page](https://configu.com/docs/nodejs-sdk/) and seeing that you can successfully work with `JsonFileConfigStore`. Use a clean project and follow the snippets. Once you get an understanding of how to use the SDK interfaces you can start to play around with the node package in this repository and implement this feature.

If you encounter any issues, I recommend that you join our [community discord](https://discord.com/invite/cjSBxnB9z8) and contact us there for help with any specific problem you might encounter.

**Comment by Maran1947** [comment]
Thank you! I'll proceed with it, and if any issues arise, I'll reach out to you for assistance.
