### ISSUE TITLE
Add missing documentation tags in the README.md file 

### ISSUE THREAD

**Issue by 7h3-3mp7y-m4n** [configu/configu#274]
**Description**
There are few more tags missing in the Readme.md file which are mentioned in the document section of the website ex ( Configu clouds etc)

**Motivation**
It would create a balance between website documentation  linkage with the Readme.md file 
**Additional context**
<img width="1440" alt="Screenshot 2023-10-03 at 10 26 22 PM" src="https://github.com/configu/configu/assets/115151332/83d90f31-bd0c-48ed-8027-143735dd2c42">
<img width="1440" alt="Screenshot 2023-10-03 at 10 19 29 PM" src="https://github.com/configu/configu/assets/115151332/d4e382ae-d345-414c-a1fc-0e192cf9d606">

**Comment by 7h3-3mp7y-m4n** [comment]
If it is valid then I would like to work on it

**Comment by beKoool** [comment]
Hey friend, If this issue is valid, the can I work on it?

**Comment by pelegpor** [comment]
Thank you for opening this issue and pointing out the discrepancies between our website documentation and the `Readme.md` file.

We're currently in the process of creating a more comprehensive and informative `Readme.md` file. Additionally, we're working on splitting the documentation into two distinct sections: one for the open-source aspect of Configu and another for the cloud platform. This separation should provide clearer and more relevant information for both users of the open-source tool and the cloud platform.

It's important for us to keep the Configu open-source documentation clean from commercial offerings. Configu is fully functional as an open-source tool without the need for additional tools, so the cloud platform information isn't relevant in the open-source `Readme.md`.

Regarding the IDE plugins, we'll be sure to add them to the `Readme.md` once they become available.

Again, thank you for your feedback and patience as we work to improve our documentation.
