### ISSUE TITLE
Add Gitpod environment in Readme

### ISSUE THREAD

**Issue by Smartmind12** [configu/configu#282]
**Description**

Gitpod environment allows you to view and interact with this code directly in the browser without the need to clone it to your local machine. Hence its required for ease of code and testing and thus needs to be added in the repo for community benefit!

**Motivation**

Adding this feature will help open-source contribution, testing and deployment much easier for developers.

**Additional context**

Kindly assign this issue to me so that i can add Gitpod environment in the readme.

**Comment by RichardAkman** [comment]
Hi @Smartmind12, thank you for your proposal and willingness to contribute to our project. We appreciate your enthusiasm for enhancing the open-source experience!

Our team is not particularly familiar with Gitpod, so we'd greatly value your insights and expertise in this area. Could you please provide more details about what adding a Gitpod environment entails? Specifically, we would like to know if it requires any special credentials or permissions for the repository.

In the meantime, I will promptly assign this issue to you, and we look forward to seeing your contributions. Once it's implemented, we will thoroughly review and assess its impact on our project.

Your dedication to improving the open-source experience is truly commendable, and we are excited to collaborate with you on this endeavor. If you have any additional questions or require any assistance, please don't hesitate to reach out. Thank you for your support!

**Comment by Smartmind12** [comment]
Hey @RichardAkman Gitpod is an open-source Kubernetes application for ready-to-code cloud development environments that spins up fresh, automated dev environments for each task, in the cloud, in seconds directly from Desktop IDE or Browser. 
1. Automation, version-control, and sharing of dev environments with the team is easily possible and repeatable.
2. User can control how Gitpod pre-configures and initializes environments before you even start a workspace through init commands in your .gitpod.yml
3. Dedicated workspace for the user to code, test and document and the same workspace can also be shared with others.
4. Gitpod instantly starts a container in the cloud based on your Docker image and seamlessly connect with git hosting platform like GitHub, GitLab and Bitbucket.
5. Easy and hassle free native code reviews on any PR/MR can be carried out on gitpod.

It does not requires any special credentials or permissions for the repository. 

User does not need to download the code/ repo in the local system and can do it all online. With the click of a gitpod button on readme, the whole repo is cloned and automatically dependencies and modules are initiated without having to add code in the terminal to initiate the process. A port is assigned once the code run has been successful so that the user can access the website through this port and make necessary additions or conduct testing of the same.
