### ISSUE TITLE
Changing Website Theme from Dropdown Menu to Toggle Button

### ISSUE THREAD

**Issue by moheyt** [configu/configu#294]
**Description**
Website currently offers users the ability to switch between light, dark, and system theme modes through a dropdown menu. However, this approach is not user-friendly and could be significantly improved. To enhance the user experience and keep up with modern web design trends, we propose changing the website theme selection mechanism from a dropdown menu to a toggle button.

![Uploading Screenshot 2023-10-24 215632.png…]()

Steps to Reproduce:

1. Visit our website.
2. Navigate to the theme selection section.
3. Observe that the user is presented with a dropdown menu to select the theme.
Note that users need to click on the dropdown, choose a theme, and then click again to apply the selected theme.

Expected Behavior:

Users should be able to switch between website themes with a single click, providing a more intuitive and efficient experience.

Suggested Solution:

Replace the existing dropdown menu with a toggle button that allows users to switch between light, dark, and system themes effortlessly. The toggle button should have clear visual indicators for the selected theme and provide real-time feedback upon theme selection.

Benefits of Implementing the Suggested Solution:

1. Improved User Experience: A toggle button is more intuitive and user-friendly than a dropdown menu, making it easier for users to switch themes quickly.
2. Enhanced Aesthetics: A toggle button aligns with modern design trends and can improve the visual appeal of the website.
3. Efficiency: Users can switch themes with a single click, saving time and reducing friction.
4. Consistency: The toggle button better matches user expectations, as it is commonly used for theme selection on various websites and applications.

**Comment by ashutuptiwari** [comment]
If  @moheyt  removes his assignment in the future, assign this to me. Emphasis on 'if'

**Comment by adarsh-jha-dev** [comment]
Hey @moheyt , could you please assign me this issue?

**Comment by rannn505** [comment]
The [configu.com](configu.com) website is not related to this repo.

The new docs portal at [docs.configu.com](docs.configu.com) currently have this kind of button
<img width="1442" alt="image" src="https://github.com/user-attachments/assets/1972add3-62bb-403f-881e-6926275d8968">
