### ISSUE TITLE
Fix Windows dependency installation

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#306]
### Current Behavior

When performing a clean dependency installation within the root directory on a Windows machine, the following error occurs:
```
[ts]
[vscode] Error: TypeScript error: File 'types/*.ts' not found.
[vscode]   The file is in the program because:
[vscode]     Root file specified for compilation.
[vscode] npm run prepare:vscode exited with code 1
```

### Expected Behavior

The dependencies should be installed successfully.

### Steps To Reproduce

Run `npm i` on a clean clone/fork of the repository on a Windows machine.

### Anything else?

- This issue has been reproduced on both Windows 10 with node 18.18.2 and Windows 11 with node 18.17.1
- This issue seems to have something to do with Windows terminals not supporting wildcards. Specifically with this command: `"quicktype --src-lang typescript --src ./types/*.ts"`, when changing this command to use the files explicitly, the issue is resolved.

**Comment by rannn505** [comment]
quicktype has been deprecated for the project so this issue is not relevant anymore. thanks @RichardAkman
