### ISSUE TITLE
Configu Login is stuck in Ubuntu 22.04

### ISSUE THREAD

**Issue by msbuk** [configu/configu#309]
### Current Behavior

```
 configu login
Press any key to open up the browser to login or press ctrl-c to abort.
  You should see the following code: xxx xxx xxx. It expires in 15 minutes.:
```

Configu login is been stuck and it is not giving the URL nor opening the url in browser,

I am using windows 11 and SSH my AWS UBUNTU 22.04 machine via putty

### Expected Behavior

Configu login should pop up the default browser of windows and should made the login, if it is linux how the things ll be done ?

### To Reproduce

I am trying out in ubuntu 22.02 OS

**Comment by RichardAkman** [comment]
Hi @msbuk ,

I understand the issue you're encountering with the `Configu login` command on a remote virtual machine. Working from a remote shell limits access to the browser, causing the command to get stuck.

For this scenario, using the Configu login command won't serve your purpose. Instead, I'd recommend generating a [Configu token from the Configu cloud platform](https://configu.com/docs/tokens) and setting up your CLI credentials as outlined in the [CLI configuration documentation](https://configu.com/docs/cli-config/). This approach will allow your CLI to communicate with your Configu config store effectively.

To clarify, you'll need to adjust your `.configu` file with the appropriate credentials. Here's an example configuration:

```
{
  "stores": {
    "configu": {
      "type": "configu",
      "configuration": {
        "credentials": {
          "org": "your-org-id",
          "token": "your-token"
        }
      }
    }
  }
}
```

By configuring the `.configu` file in this manner, you'll be able to seamlessly interact with your Configu config store as you would after configu login.

Let me know if you encounter any issues while implementing this approach.

**Comment by msbuk** [comment]
Yes .configu i have figured out 2 days before itself , That works

I have a another doubt like configu cloud is limited for various use case right and configu operator is open source,

any clear document is there , how we can integrate entirely (end to end CI CD ) with opensource / cloud ?

Still documentation could more granular, but fine, Just i need a clarity how we can use open source entirely with unlimited features ??

**Comment by RichardAkman** [comment]
It's good to hear that you manage to make it work. We know that the documentation needs more refinement and fine-tuning, including examples of how to utilize the CLI in your specific use case effectively. We are hoping to launch a new, more robust, documentation portal at the beginning of next month.

Since there is no actual problem with the CLI, I'll close this issue.

If you need help with a specific function using the open-source tools or the cloud platform, please feel free to ask in our Discord server and the community will help you out.
