### ISSUE TITLE
Split python SDK dependencies by config stores

### ISSUE THREAD

**Issue by jamesL92** [configu/configu#316]
### Suggestion

_More a point of discussion/idea rather than a concrete feature request. If this is not the direction Configu wishes to go in then please feel free to close this issue_

Python dependency resolution supports the concept of package "extras" - we could split the dependencies by config store, where individual config stores/sets of similar config stores could be packaged as "extra" dependencies. e.g. the `boto3` dependencies could be installed via "configu[aws]".

### Motivation

With an ever increasing number of config store providers, the SDK's dependency tree will continue to increase going forward. This leads to:
- Increased dependency resolution time
- Increased likelihood of version incompatibilities with other packages

As far as I'm aware users will typically only require a single type of config store, in some cases at most 2-3 types. Thus most users won't actually require the ability to support _all_ config store types.

### Context

https://python-poetry.org/docs/pyproject/#extras

Running on Ubuntu Linux, installing a fresh project with only `configu` as a dependency took 15 minutes.

**OS/Arch**: Linux 20.04.1-Ubuntu x86_64`

pyproject.toml:
```
[tool.poetry]
name = "consumer"
version = "0.1.0"
description = ""
authors = ["lucas <xxx@xxx.xxx>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
configu = "^0.6.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

poetry version: 1.5.1
python version: 3.9.16

Installation time: 942.7s
(Package operations: 53 installs, 1 update, 0 removals)

**Comment by rannn505** [comment]
The `Python SDK` is deprecated in favor of the `@configu/proxy` server.
