### ISSUE TITLE
Research: CLI Scanner (find) 

### ISSUE THREAD

**Issue by RonConfigu** [configu/configu#338]
### Suggestion

CLI command `find` should find in-code usages of ENV_VARS and export to .cfgu

### Context

Looking into it, seems like AST is the natural solution, Regex may be valid for simple cases but in order to actually find and trace complex usage of in-code env vars I feel like we should be able to "understand" the code a lot more than just read it.
@rannn505 suggested `ast-grep` lib for this task and or abstract ML/AI.
While ML/AI is obviously able to "understand" the code faster and better than any algo we could build, currently we can't afford the time developing it.
`ast-grep` on it self, doesn't provide the necessary tools in my opinion, yet, it relies on 'tree-sitting' lib which seems perfectly fit to handle the job of parsing AST trees for various languages.

That being said, I've spent some time with `tree-sitting` parsing simple TS/JS code and playing with s-expressions queries, seems doable to cover a lot of use cases.
Our comunity can add and improve the queries to match more and more cases.
Below are screenshots of example code and queries

![image](https://github.com/configu/configu/assets/129258356/7930959f-fba1-4250-8b42-32c8c5b6c20f)
![image](https://github.com/configu/configu/assets/129258356/0bed4e37-5e8e-4197-a8fe-67431d19bacd)

**Comment by rannn505** [comment]
Currently implemented as `find` command at the cli.
This feature will be expanded in the near future.
