### ISSUE TITLE
Onboarding uses wrong filename "get-started" vs "start"

### ISSUE THREAD

**Issue by mdp** [configu/configu#342]
### Current Behavior

Onboarding says

```
configu upsert \
--store 'configu' --set 'Development' --schema './get-started.cfgu.json' \
--config 'GREETING=hey' -c 'SUBJECT=Mark Percival' \
&& configu upsert \
--store 'configu' --set 'Development/QA' --schema './get-started.cfgu.json' \
-c 'GREETING=welcome'
```

But not the 'get-started' flag actually names the config file 'start.cfgu.json' - https://github.com/configu/configu/blob/3ebb70dcadaaa01629387963f7c790a430498ffb/ts/packages/cli/src/commands/init.ts#L94

### Expected Behavior

```
configu upsert \
--store 'configu' --set 'Development' --schema './start.cfgu.json' \
--config 'GREETING=hey' -c 'SUBJECT=Mark Percival' \
&& configu upsert \
--store 'configu' --set 'Development/QA' --schema './start.cfgu.json' \
-c 'GREETING=welcome'
```

### To Reproduce

Go through the onboarding process, try to run the upsert and eval commands as stated.

### Context

Onboarding flow

**Comment by RichardAkman** [comment]
Thank you for bringing this to our attention! I've created an issue for this in the configu documentation repository and linked this issue to it. This is an issue exclusive to our docs so I will be closing this one. Let me know if you're interested in contributing and I'll assign the issue to you. If not, we will take care of it as soon as possible.

**Comment by rannn505** [comment]
This issue has been resolved with the recent release
The fix has been tested and confirmed to be working as expected.
If you encounter any further issues or have additional questions, please feel free to open a new issue or comment on this thread.

<img width="680" alt="image" src="https://github.com/user-attachments/assets/f723f30e-7b7f-4b9f-a078-7e7fa9757e9b">
