### ISSUE TITLE
Add `--prefix` and `--suffix` Flags to ExportCommand in CLI

### ISSUE THREAD

**Issue by rannn505** [configu/configu#358]
### Suggestion

Enhance the `ExportCommand` functionality in the CLI by introducing two new optional flags: `--prefix` and `--suffix`. These flags will allow users to append a fixed string to the beginning (`--prefix`) or end (`--suffix`) of each Config Key in the export result.

Example Usage:
```bash
conifgu eval ... | configu export --prefix "MYAPP_" --suffix "_PROD"
```
In the above example, if we have a Config Key named `DATABASE_URL`, the export result would transform it into `MYAPP_DATABASE_URL_PROD`. This functionality is particularly useful when different environments or systems require specific naming conventions for configuration keys.

### Motivation

The addition of `--prefix` and `--suffix` flags will provide users with greater control over the format of their exported configuration keys, making it easier to adapt the output for different deployment environments or system requirements.

### Context

connected to #333 

```js
    prefix: Flags.string({
      description: `Append a fixed string to the beginning of each Config Key in the export result`,
    }),
    suffix: Flags.string({
      description: `Append a fixed string to the end of each Config Key in the export result`,
    }),
```

**Comment by RonConfigu** [comment]
## Development Plan
- [x] Research
- [x] Add example to examples in `cli/commands/export.ts`
- [x] Add `prefix` and `suffix` flags to `configu export`
- [x] Create function `keysMutations` -> this func will return undefined if no --prefix or --suffix is requested or a `(key:string)=>string` if do. Using function is not necessary here but it's a prep for [#359](https://github.com/configu/configu/issues/359)
- [x] Add `keys:keysMutations()` to `ExportCommand` params
- [ ] Update docs (if necessary)

## Questions / Requests

### Notes / Comments / Additional
- As requested by @rannn505, [Casing](https://github.com/configu/configu/issues/359) will apply last. Including the prefix and suffix
