### ISSUE TITLE
Extend `Date Time` Cfgu Types

### ISSUE THREAD

**Issue by rannn505** [configu/configu#373]
### Suggestion

- Durations: 1h, 2d, etc..
- date formats etc..

**Comment by Aman1919** [comment]
@rannn505  Can u i work on this ?

**Comment by pelegpor** [comment]
@Aman1919 you got it!

**Comment by JayGaba** [comment]
@pelegpor could i take it up since i am working on a similar issue as well?

**Comment by JayGaba** [comment]
@pelegpor please review the changes, thank you!

**Comment by JayGaba** [comment]
@pelegpor please review the changes, thank you!
