### ISSUE TITLE
Make all `cfgu` properties optional

### ISSUE THREAD

**Issue by rannn505** [configu/configu#437]
### Suggestion

 Make all `cfgu` properties optional so the minimum `ConfigSchema` will only hold the `ConfigKeys` it manages.
 

### Motivation

This change will reduce complexity and enhance flexibility, allowing users to define configurations without mandatory fields that may not be relevant to their specific use cases. This approach supports more lightweight and tailored configuration management, improving usability and adoption.

### Context

Current configurations include mandatory `cfgu` properties like `type` that may not be necessary for all users. 
By making these properties optional, we align with user feedback requesting a more minimalistic and adaptable schema. 
This feature is expected to be backward compatible, ensuring existing configurations remain functional without modification.

https://docs.configu.com/interfaces/.cfgu

**Comment by jamesL92** [comment]
Looking at the current `cfgu` interface, it seems the only property that's currently non-optional is `type`.

Am I right in thinking the approach to this would be to default `type` to `"String"`, which effectively allows any value? Or is the ask for this feature more complex than that?

**Comment by RichardAkman** [comment]
Hi @jamesL92, this issue is part of the motivation behind the recent rework done to the repository architecture and is one of the changes introduced in `@configu/sdk` which makes all `cfgu` properties optional.

Closing this issue as it was already accomplished.
