### ISSUE TITLE
Introduce a `cfgu` keyword for applying complex validation on a `ConfigValue`

### ISSUE THREAD

**Issue by rannn505** [configu/configu#438]
### Suggestion

Introduce a `cfgu` keyword for applying complex validation on a `ConfigValue`. 
Example usage:

  ```yaml
  KEY:
    test: Int({gt: 6})
  ```

### Motivation

Adding such a keyword will significantly enhance the `cfgu` capabilities by allowing users to specify detailed validation rules. This feature supports use cases where simple type validation is insufficient and more complex conditions need to be enforced.

### Context

This feature will be backed by an expression syntax derived from JavaScript, specifically utilizing the Adaptive Expressions library provided by Microsoft (https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-expressions). This library offers a robust and flexible framework for defining complex validation rules and will serve as the foundation for implementing this feature.

Related: #337  #374 

TBD: @rannn505 
- decide on the name of this keyword. `validation` | `check` | `test` | `format`

**Comment by jamesL92** [comment]
Two questions:
1. Couldn't find any reference to anything like `Int({gt: 6})` in the `adaptive-expressions` documentation linked. (specifically the `{gt: 6}` bit
2. Might need to be more specific on scope/constraints/etc here...`adaptive-expressions` appear to manage far more than just validation - it appears to also provide transformation logic too - see [this](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-concept-adaptive-expressions?view=azure-bot-service-4.0&tabs=arithmetic#language-generation) for example.

If we do want to make use of the `adaptive-expressions` library specifically, I'd suggest either:
1. We try to scope this down to validation statements only (i.e. only adaptive expressions that MUST return a boolean)
2. We try to use this more broadly, such as for things like templating/etc. Main reason I suggest this is that it's going to be more intuitive for users to only have to deal with one framework's syntax (we already have e.g. Mustache for templating). If we go down this approach though I feel like it'd be a somewhat larger feature that'll need a somewhat more overall strategic approach.

**Comment by RichardAkman** [comment]
Hi @jamesL92, this issue is part of the motivation behind the recent rework done to the repository architecture and is one of the changes introduced in `@configu/sdk` via the `test` property of the new `Cfgu`. We will be going with the approach that has the expression string reduced down to a boolean.

Closing this issue as it was already accomplished.
