### ISSUE TITLE
Enable glob-based paths for `ConfigSchema`s

### ISSUE THREAD

**Issue by rannn505** [configu/configu#440]
### Suggestion

Enable glob-based paths for `ConfigSchema`s in the `.configu` file and with the `--schema` flag on the CLI. When a glob path is used, the interface will expand it, and if multiple schemas are found, it will combine them. If a key is in multiple schemas, the "deepest" one takes precedence.

### Motivation

Simplifies managing multiple schemas by allowing pattern-based file selection. Useful for projects with hierarchical or scattered configurations. Ensures specific configurations override general ones.

### Context

Currently, users must specify each schema file individually, which can be cumbersome and error-prone, especially in large projects with many configuration files. By allowing glob-based paths, we streamline the process, making it easier to manage and apply multiple schemas. This is particularly useful in environments where schemas are organized in a directory structure that reflects their scope and specificity.

For instance, a user might have a directory structure where common schemas are in a top-level directory, and more specific schemas are nested deeper. By using a glob pattern, such as schemas/**/*.yaml, the interface will automatically include all relevant schemas. If a key is declared in multiple schemas, the rule that the "deepest" one wins ensures that the most specific configuration is applied.

**Comment by jamesL92** [comment]
I'd be happy to have a go at implementing this :)
Although there are definitely some edge cases to think about here.

In terms of conflicting keys, how do we want to handle conflicts where the files are of an equal depth?
For example, say we have a conflict between `<root>/dir1/schema1.cfgu.json` and `<root>/dir2/schema2.cfgu.json`, how would we determine which takes precedence?

I think there's a few approaches we could take here, including:
- Last-Alphabetical-Absolute-Path, which would match the order a glob expansion would typically return (so dir2 takes priority).
- First-Alphabetical-Absolute-Path, the inverse of above
- Include an optional "priority" key  per-config, so users can specify decide for themselves which takes precedence
- Explicitly raise an exception if there is a conflict, and the two keys don't perfectly match each other

I suspect there are other edge cases to consider (particularly around _templated_ keys), as well as impacts on #337 and #438 


As well as a glob pattern, I wonder if it might be a good idea to allow users to provide a list of paths, which would allow interaction between this feature and #439
