### ISSUE TITLE
Implement `INI` ConfigFormatter

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#452]
### Suggestion

introduce an `INI` file config formatter. 

### Motivation

Enhancing the flexibility of our formatters suite and catering to users of `INI` files.

### Context

- Install the [ini](https://www.npmjs.com/package/ini) package
- Refer to this [PR](https://github.com/configu/configu/pull/253/files) as a previous formatter implementations. 

Example usage:
```bash
configu eval ... | configu export --format 'INI'
```

**Comment by michaldziuba03** [comment]
I would like to be assigned, I already made PR: #467

**Comment by davidmeirlevy** [comment]
@michaldziuba03 it's yours :)
