### ISSUE TITLE
Merge `CompactJSON` formatter with `JSON` formatter

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#453]
### Suggestion

Currently, there are two distinct versions of the `JSON` formatter. Instead, we should merge both versions into a single `JSON` formatter which by default prints the "compact" version and we should extend the formatter interface to accept parameters that modify the output to support the previous `JSON` formatter that printed the output in a "pretty" variation.

### Motivation

- There shouldn't be duplications of formatters, this is a source of confusion for users.
- The default format of formatters should be as unopinionated as possible, "prettified" outputs are inherently opinionated.
- Creating an extensible interface for formatters behavior modifications allows the user to control how they want the formatted to behave which enables the user to customize their behavior.

### Context

This issue follows up on #238.

**Comment by davidmeirlevy** [comment]
Can you elaborate on how to pass arguments to the formatter?

Thanks.

**Comment by jamesL92** [comment]
Happy to take this one on if we can agree on an approach.

One possible option I'm thinking of would be to add an optional `pretty` flag to the export command. Some considerations with this approach:
- We could make it depend on the `format` flag.
- While for the vast majority of formats this flag wouldn't do anything, it'd be a nice way to extend the pretty-vs-compact versions of other configs. For example, in case of the `KubernetesConfigMap` format, it could be the difference between printing out the metadata vs. not.

Another possible approach would be to have a `format-options` flag where we can pass options that are specific to that format. So usage would be something like `configu eval ... | configu export --format JSON --format-options "pretty=true"`. We could either require format options in key-value pairs or as a json object, e.g. `--format-options "{\"pretty\": true}".

**Comment by jamesL92** [comment]
I've raised draft PRs for the two suggested approaches in case you want to compare/contrast the two approaches.

**Comment by rannn505** [comment]
@jamesL92 So happy to have your creative thoughts at the Configu table! I'm assigning this to you, but let’s meet first—I’d like to introduce the behind-the-scenes rewrite we’re working on to ensure your contribution is as effective as possible.

For the current setup, I think the `--pretty` flag is the most user-friendly solution, so we can go ahead and merge it, then consider this option for the rewrite.

**Comment by jamesL92** [comment]
@rannn505 thanks for the input, I'll go ahead and clean up the PR I've got for the `--pretty` flag and close the `--configOptions` PR for now.

Will reach out separately for a meeting :)
