### ISSUE TITLE
Update docs `Configs Explorer` page screenshots

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#456]
### Current Behavior

Some of the current screenshots in the `Configs Explorer` page are outdated and misaligned due to the recent docs updates from #443 and #451. 

### Expected Behavior

For alignment, the screenshots should reflect the new features from the same Configu organization as the rest of the docs, and all the screenshots should reflect the latest state of the platform.

**Comment by SanchitMahajan236** [comment]
I would love to work on this issue. Can you please assign me this issue under hacktoberfest tag ?

**Comment by rannn505** [comment]
Assigned to you @SanchitMahajan236! 😊 Are you familiar with what needs to be done, or would you like any further assistance?

**Comment by SanchitMahajan236** [comment]
I explored the Configs Explorer page in docs before expressing my interest to contribute. So, I am aware of what needs to be done. In case, I require further assistance I would definitely reach out to you via this chat. 

Thank you 😊
