### ISSUE TITLE
Add the 2024 Hacktoberfest Banner to the README

### ISSUE THREAD

**Issue by rannn505** [configu/configu#459]
### Suggestion

Add the official Hacktoberfest 2024 Configu banner to the README. 
Use the new attached banner file to complete the task.

### Motivation

Updating the README with the 2024 Hacktoberfest banner promotes the event and shows Configu's involvement in the open-source community.

### Context

The README contains a [comment on line 1](https://github.com/configu/configu/blob/main/README.md?plain=1#L1) with last year’s banner as a starting point.

![hacktoberfest-24-banner](https://github.com/user-attachments/assets/22d1b1fe-6812-40d8-b82c-b1726ea7039b)

**Comment by davidmeirlevy** [comment]
@rannn505 
can I take this issue, please?

**Comment by rannn505** [comment]
Let Hacktoberfest begin @davidmeirlevy

**Comment by davidmeirlevy** [comment]
@rannn505 can you please approve my PR?
