### ISSUE TITLE
Implement `Slug` Cfgu Type

### ISSUE THREAD

**Issue by rannn505** [configu/configu#460]
### Suggestion

Add a `Slug` type to the Cfgu type system of Configu.

Using `type: Slug` in a ConfigSchema should enforce a valid [Slug](https://www.npmjs.com/package/slugify) as a config value at `upsert` or `eval`.
```json
{
  ...
  "CONFIG_KEY": {
    "type": "Slug"
  }
  ...
} 
```

### Motivation

Extending Configu's type system capabilities.

### Context

- https://github.com/validatorjs/validator.js
- https://configu.com/docs/cfgu/
- https://github.com/configu/configu/blob/main/types/Cfgu.ts
- https://www.npmjs.com/package/slugify

**Comment by michaldziuba03** [comment]
I would like to be assigned to this issue

**Comment by davidmeirlevy** [comment]
@michaldziuba03 go for it! 🥇
