### ISSUE TITLE
Add Tests for `ConfigSet` Class

### ISSUE THREAD

**Issue by rannn505** [configu/configu#461]
### Suggestion

Explore the ConfigSet class to understand its functionality and write test cases that cover its various methods and edge cases. This will improve code quality and ensure the class behaves as expected.

### Motivation

Adding unit tests for the ConfigSet class improves test coverage and code reliability, making it a good introductory task for learning the class and contributing to Configu's test suite.

### Context

- [ConfigSet Class](https://github.com/configu/configu/blob/main/packages/ts/src/ConfigSet.ts)  
- [ConfigSet.test.ts](https://github.com/configu/configu/blob/main/packages/ts/src/ConfigSet.test.ts)
- [Node.js Test Runner](https://nodejs.org/api/test.html)
- [Node.js Assertion Testing](https://nodejs.org/api/assert.html)

**Comment by Mila2999** [comment]
I would like to take this issue, please!

**Comment by davidmeirlevy** [comment]
@Mila2999  thanks for your interest in our project!
I'm assigning you to this issue.

For any questions, feel free to tag me or any other project members.

Here are some examples of valid test cases:
1. should throw an error when the path includes special characters.
2. should throw an error when the path includes reserved names  ('_', '-', 'this', 'cfgu')

**Comment by rannn505** [comment]
Let us know if you need further help @Mila2999

**Comment by Mila2999** [comment]
Hi @rannn505 and @davidmeirlevy I open PR,  please take a look at my tests

**Comment by davidmeirlevy** [comment]
@Mila2999 thanks for your contribution!  I Approved the PR.
