### ISSUE TITLE
Implement `CSV` ConfigFormatter

### ISSUE THREAD

**Issue by rannn505** [configu/configu#462]
### Suggestion

introduce a `CSV` file config formatter.

### Motivation

The CSV format is widely used, and adding it as a formatter will make Configu more versatile. 

### Context

- Install the [csv](https://www.npmjs.com/package/csv) package
- Refer to this [PR](https://github.com/configu/configu/pull/253/files) as a previous formatter implementations. 

Example usage:

```bash
configu eval ... | configu export --format 'CSV'
```

**Comment by ovindu-a** [comment]
Hi, @rannn505 I would like to work on this

**Comment by rannn505** [comment]
Assigned to you @ovindu-a! 😊

**Comment by ovindu-a** [comment]
Thank you, I will start working on it

**Comment by ovindu-a** [comment]
@rannn505 I am having an issue when trying to commit the changes. I think it's a problem with how I installed the csv package. 

<img width="1317" alt="image" src="https://github.com/user-attachments/assets/cd1efeaa-e977-4864-a934-1d61c0ec676b">

This is the error. Do you have an idea how I can work around this?

**Comment by akshay11298** [comment]
Hi @rannn505 , sorry I didn't realise someone was working on it and I raised a PR https://github.com/configu/configu/pull/483 for this issue.
I had a query, currently the input json has one object, so its expected for the csv to have one row with header or is there something else too?

**Comment by ovindu-a** [comment]
@akshay11298 ohh I see, mistakes happen that's fine. I've been working on this for a while as I was assigned this. So maybe you could work on another issue?

**Comment by akshay11298** [comment]
@ovindu-a yes sure, if you are already progressed with your changes, its fine by me :)
