### ISSUE TITLE
convert integrations to import sdk instead of ts lib

### ISSUE THREAD

**Issue by davidmeirlevy** [configu/configu#493]
### Suggestion

currently, all integration were written using the old API.
they are importing `@configu/ts`.
they should import new data from `@configu/sdk`

**Comment by akshay11298** [comment]
Hi @davidmeirlevy , is this issue open for community? If yes, can I work on it?

**Comment by davidmeirlevy** [comment]
hi @akshay11298 , this is an internal change that we need to finish the refactor, so others can contribute to the new version of the CLI, so I already did it.
but thanks for your enthusiasm!
our next ticket will be easier after this refactor.

**Comment by RS-labhub** [comment]
@davidmeirlevy open new issues ... Waiting for it!
