### ISSUE TITLE
Migrate `PostgreSQLConfigStore` to `@configu/integrations`

### ISSUE THREAD

**Issue by rannn505** [configu/configu#508]
### Suggestion

Migrate the `PostgreSQLConfigStore` from its current setup to the new `@configu/integrations` module as part of the major restructuring. The goal is to move all third-party integrations, including stores, expressions, and libraries, to `@configu/integrations`.

### Motivation

This migration is part of a larger effort to better organize and modularize the product. Moving the `PostgreSQLConfigStore` will align with the new structure, making the system cleaner and more maintainable.

### Context

You can refer to the already migrated stores for guidance:  
[Migrated stores in integrations](https://github.com/configu/configu/tree/main/packages/integrations/stores).

Base stores implementations from `@configu/ts` can be found here:  
[Base stores in TS](https://github.com/configu/configu/tree/52cee9c41fb03addc4c0983028e37df42945f5b7/packages/ts/src/stores).

The old node-based stores were previously in `@configu/node`:  
[Node stores](https://github.com/configu/configu/tree/52cee9c41fb03addc4c0983028e37df42945f5b7/packages/node/src/stores).

The old browser-based stores were previously in `@configu/browser`:  
[Browser stores](https://github.com/configu/configu/tree/52cee9c41fb03addc4c0983028e37df42945f5b7/packages/browser/src/stores).

**Comment by ayan-joshi** [comment]
@rannn505 Hey I would like to work on it

**Comment by TomerPacific** [comment]
@rannn505 - Is this issue still relevant?

**Comment by RichardAkman** [comment]
@TomerPacific, it is, since @ayan-joshi hasn't progressed with this issue since being assigned we will switch the assignment to you. Good luck!

**Comment by TomerPacific** [comment]
Thanks @RichardAkman. Anything else I should be aware of besides what is written in the issue? Anything I should know in advance before setting up a local development environment?

**Comment by RichardAkman** [comment]
Nothing in particular, make sure to take reference from recently merged store integrations.

**Comment by TomerPacific** [comment]
@RichardAkman - Posted a message in Discord. Would appreciate it if you could give it a look.

**Comment by TomerPacific** [comment]
@RichardAkman - Thanks for all the help. I have opened a PR [here](https://github.com/configu/configu/pull/605)

**Comment by ayan-joshi** [comment]
@RichardAkman so sorry was quite busy with college work didnt responded

**Comment by RichardAkman** [comment]
@ayan-joshi no problem, feel free to pick up any other unassigned issue once you're free to contribute.
