### ISSUE TITLE
Migrate `CloudBeesConfigStore` to `@configu/integrations`

### ISSUE THREAD

**Issue by rannn505** [configu/configu#512]
### Suggestion

Migrate the `CloudBeesConfigStore` from its current setup to the new `@configu/integrations` module as part of the major restructuring. The goal is to move all third-party integrations, including stores, expressions, and libraries, to `@configu/integrations`.

This migration requires to migrate also the BaseStore of `OpenFeatureConfigStore` to `integrations/src/utils` same as the `FileConfigStore`, `ORMConfigStore` etc.

### Motivation

This migration is part of a larger effort to better organize and modularize the product. Moving the `CloudBeesConfigStore` will align with the new structure, making the system cleaner and more maintainable.

### Context

You can refer to the already migrated stores for guidance:  
[Migrated stores in integrations](https://github.com/configu/configu/tree/main/packages/integrations/stores).

Base stores implementations from `@configu/ts` can be found here:  
[Base stores in TS](https://github.com/configu/configu/tree/52cee9c41fb03addc4c0983028e37df42945f5b7/packages/ts/src/stores).

The old node-based stores were previously in `@configu/node`:  
[Node stores](https://github.com/configu/configu/tree/52cee9c41fb03addc4c0983028e37df42945f5b7/packages/node/src/stores).

The old browser-based stores were previously in `@configu/browser`:  
[Browser stores](https://github.com/configu/configu/tree/52cee9c41fb03addc4c0983028e37df42945f5b7/packages/browser/src/stores).

**Comment by Prathamesh010** [comment]
Please assign me this issue

**Comment by RichardAkman** [comment]
All yours @Prathamesh010
