### ISSUE TITLE
Implement `configu generate` Command in `@configu/cli`

### ISSUE THREAD

**Issue by rannn505** [configu/configu#528]
### Suggestion

Implement the `configu generate` command with `--dir` and `--name` flags. This command will create an integration module in the specified directory, ready to be injected into the system.

### Motivation

Simplifies the creation of integration modules by automating the setup process. Developers can quickly generate the necessary files and structure with a single command, improving productivity and reducing manual setup effort.

### Context

The `configu generate` command will take a directory (`--dir`) and module name (`--name`) as inputs, creating a pre-configured integration module that is ready for injection into the project.

**Comment by lyle45** [comment]
I would like to do it

**Comment by davidmeirlevy** [comment]
@lyle45 you got it :)

**Comment by davidmeirlevy** [comment]
@lyle45 are you still on it?
because we want to deliver this feature soon.

**Comment by lyle45** [comment]
@davidmeirlevy hi David. Sorry was preoccupied. Will do it today hopefully

**Comment by davidmeirlevy** [comment]
if you need any help with that, don't hesitate to reach me on our discord channel.

**Comment by davidmeirlevy** [comment]
@lyle45 I see that it takes too much, and this is a very core feature of configu that we must deliver very soon.
So I need to re-assign it.

**Comment by jamesL92** [comment]
Im happy to pick this up :)

**Comment by davidmeirlevy** [comment]
@jamesL92 you can checkout from my branch..

**Comment by lyle45** [comment]
@davidmeirlevy yeah my apologies. Couldn't get to it. Sorry
