### ISSUE TITLE
Verify that every integration build creates one-file only

### ISSUE THREAD

**Issue by davidmeirlevy** [configu/configu#535]
### Suggestion

a test, of an after-build step for every integration, to verify that the integration bundle created only one-file.

### Motivation

it seems like some store integrations tend to create a bundle that has more than one file, which leads to runtime errors when we want to lazy-load those integrations on demand.

### Context

when you can "pnpm build:integrations" on the root folder, you can then go to "packages/integrations/dist" and to view all integrations bundles.
the command i mentioned runs all build scripts of all internal integration packages inside the "integrations" library in parallel.
each one creates its own package bundle.

this error might occur if the tsup config is not accurate, or missing external dependencies.

**Comment by davidmeirlevy** [comment]
another simple way to is to add `splitting: false,` to every tsup.config.ts file :)

**Comment by JayGaba** [comment]
hi @davidmeirlevy, can you assign this to me please
