### ISSUE TITLE
Add Contributors Section to README with Dynamic Image

### ISSUE THREAD

**Issue by pelegpor** [configu/configu#555]
### Suggestion

Add a section to the README file featuring our amazing contributors.

### Motivation

Recognizing and highlighting the efforts of contributors is essential for fostering a strong, inclusive open-source community. Adding a contributors section will show appreciation to the individuals who have dedicated time and effort to improve Configu, encouraging more involvement from the community.

### Context

The section should be placed at the bottom of the README file to ensure visibility without interrupting the flow of the document. This will make it clear and easy for users to see who has contributed to Configu.

Image Source: https://contributors-img.web.app/image?repo=configu/configu

### The section should look like this:
```
## 🙌 Thanks to all of our contributors

A huge thanks for spending your time and energy helping Configu grow! 🌱 Your contributions are incredibly valued.  

<img src="https://contributors-img.web.app/image?repo=configu/configu" alt="Contributors"/>
```

Preview:
## 🙌 Thanks to all of our contributors

A huge thanks for spending your time and energy helping Configu grow! 🌱 Your contributions are incredibly valued.  

<img src="https://contributors-img.web.app/image?repo=configu/configu" alt="Contributors"/>

**Comment by i-sanjay-cs** [comment]
@pelegpor Assign me !

**Comment by pelegpor** [comment]
@i-sanjay-cs you got it 👍
