### ISSUE TITLE
"Join Chat 💬" Link in README Redirects to Docs Instead of Discord

### ISSUE THREAD

**Issue by pelegpor** [configu/configu#556]
### Current Behavior

The "Join Chat 💬" link in the README file redirects to the documentation page instead of the Configu Discord server.

### Expected Behavior

The "Join Chat 💬" link should direct users to the Configu Discord server at [https://discord.com/invite/cjSBxnB9z8](https://discord.com/invite/cjSBxnB9z8).

### Context

- The issue is present on line 27 of the README.
- Incorrect link redirects to the documentation.
- The correct link should be: [https://discord.com/invite/cjSBxnB9z8](https://discord.com/invite/cjSBxnB9z8).

**Comment by su-shubham** [comment]
Interested! @pelegpor Assign me.

**Comment by pelegpor** [comment]
@su-shubham
You got it!
