### ISSUE TITLE
Incorrect Link for "Explore Docs 📚" in README

### ISSUE THREAD

**Issue by pelegpor** [configu/configu#557]
### Current Behavior

The "Explore Docs 📚" link in the README is currently leading to the wrong destination. Instead of pointing to the documentation page, it is linked to the Getting Started guide.

### Expected Behavior

The "Explore Docs 📚" link should take users directly to the official Configu documentation page at [docs.configu.com](docs.configu.com).

### Context

- Correct URL: [https://docs.configu.com](https://docs.configu.com)
- Line number: 27

**Comment by sarika11-06** [comment]
Assign me @pelegpor !

**Comment by pelegpor** [comment]
You got it @sarika11-06 🚀
