### ISSUE TITLE
Update `inquirer` to `@inquirer/prompts` at `@configu/cli`

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#579]
### Suggestion

Change the `inquirer` dependency and usage at `@configu/cli` to `@inquirer/prompts`. 
BONUS: leverage the [`inquirer-press-to-continue` plugin](https://github.com/leonsilicon/inquirer-press-to-continue) to achieve the previous CLI iteration behavior of the `confirmLogin` step in `login` command.

### Motivation

The `Inquirer` package is now [considered legacy and is no longer being actively developed](Inquirer.js). The new package also has a smaller size which is beneficial to keep the CLI binaries leaner and general performance improvements.

### Context

- Legacy package link: https://www.npmjs.com/package/inquirer
- New package link: https://www.npmjs.com/package/@inquirer/prompts

**Comment by vickywane** [comment]
Hi @RichardAkman ,

I'd love to work on this.

**Comment by RichardAkman** [comment]
All yours @vickywane, good luck!

**Comment by vickywane** [comment]
@RichardAkman I have opened the PR for this.

**Comment by RichardAkman** [comment]
Hi @vickywane,

Thank you for submitting this PR and for your enthusiasm in contributing to our CLI! Since the related issue was opened, we've had internal discussions about our long-term strategy for handling CLI I/O. For better sustainability, maintainability, and consistency, we’ve decided to transition fully from [Inquirer.js](https://www.npmjs.com/package/inquirer) to [Consola](https://www.npmjs.com/package/consola), which is already partially integrated into our CLI. Given this shift in approach, the issue is now considered obsolete, and unfortunately, this PR no longer aligns with our direction.

We really appreciate your work on this and hope you'll continue contributing to our project. If you're interested in tackling another issue or would like guidance on where help is most needed, please feel free to reach out. Thank you again for your support and understanding!
