### ISSUE TITLE
Documentation: `AWSParameterStoreConfigStore`

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#582]
### Suggestion

Document the `AWSParameterStoreConfigStore` integration with all the necessary details that explain what the store is and how to use it.

### Motivation

- Introduces users to the [ConfigStore](https://docs.configu.com/introduction/concepts#configstore).
- Improves usability of the store by providing usage examples.
- Improves the completeness of the integration package.

### Context

- Integration docs: https://docs.aws.amazon.com/systems-manager/latest/userguide/systems-manager-parameter-store.html
- Integration SDK docs: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/ssm
- Example PR of a store doc contribution: #575

**Comment by RichardAkman** [comment]
All yours @poorvibajpai

**Comment by poorvibajpai** [comment]
@RichardAkman  Sir i have written the documentation but I'm bit confused where to paste the whole data in the repo, Please help me with this one.

**Comment by RichardAkman** [comment]
@poorvibajpai, please refer to PR #575 regarding where to place the files and how the documentation should look.
