### ISSUE TITLE
Documentation: `CloudBeesConfigStore`

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#584]
### Suggestion

Document the `CloudBeesConfigStore` integration with all the necessary details that explain what the store is and how to use it.

### Motivation

- Introduces users to the [ConfigStore](https://docs.configu.com/introduction/concepts#configstore).
- Improves usability of the store by providing usage examples.
- Improves the completeness of the integration package.

### Context

- Integration docs: https://docs.cloudbees.com/docs/cloudbees-feature-management/latest
- Example PR of a store doc contribution: #575

**Comment by Ritesh-Udgata** [comment]
Finally assign me this issue.
