### ISSUE TITLE
Documentation: `CsvFileConfigStore`

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#586]
### Suggestion

Document the `CsvFileConfigStore` integration with all the necessary details that explain what the store is and how to use it.

### Motivation

- Introduces users to the [ConfigStore](https://docs.configu.com/introduction/concepts#configstore).
- Improves usability of the store by providing usage examples.
- Improves the completeness of the integration package.

### Context

- Integration docs: https://en.wikipedia.org/wiki/Comma-separated_values
- Example PR of a store doc contribution: #575

**Comment by RS-labhub** [comment]
I would like to work on this!

**Comment by RichardAkman** [comment]
All yours @RS-labhub

**Comment by RichardAkman** [comment]
Hi @RS-labhub, just checking in since it’s been about a week. Could you let me know if you’re still working on this issue? If not, I’ll go ahead and open it up for other contributors, especially with Hacktoberfest in mind. Thanks for keeping us in the loop!

**Comment by RS-labhub** [comment]
Pushing a PR in few mins
