### ISSUE TITLE
Documentation: `EtcdConfigStore`

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#587]
### Suggestion

Document the `EtcdConfigStore` integration with all the necessary details that explain what the store is and how to use it.

### Motivation

- Introduces users to the [ConfigStore](https://docs.configu.com/introduction/concepts#configstore).
- Improves usability of the store by providing usage examples.
- Improves the completeness of the integration package.

### Context

- Integration docs: https://etcd.io/docs
- Example PR of a store doc contribution: #575

**Comment by Ritesh-Udgata** [comment]
Kindly assign this issue and thank you so much for your support today 👍

**Comment by RichardAkman** [comment]
No problem @Ritesh-Udgata, all yours
