### ISSUE TITLE
Documentation: `GCPSecretManagerConfigStore`

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#588]
### Suggestion

Document the `GCPSecretManagerConfigStore` integration with all the necessary details that explain what the store is and how to use it.

### Motivation

- Introduces users to the [ConfigStore](https://docs.configu.com/introduction/concepts#configstore).
- Improves usability of the store by providing usage examples.
- Improves the completeness of the integration package.

### Context

- Integration docs: https://cloud.google.com/secret-manager/docs
- Example PR of a store doc contribution: #575

**Comment by Ritesh-Udgata** [comment]
Kindly assign me this one .

**Comment by RichardAkman** [comment]
All yours @Ritesh-Udgata
