### ISSUE TITLE
Documentation: `KubernetesSecretConfigStore`

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#592]
### Suggestion

Document the `KubernetesSecretConfigStore` integration with all the necessary details that explain what the store is and how to use it.

### Motivation

- Introduces users to the [ConfigStore](https://docs.configu.com/introduction/concepts#configstore).
- Improves usability of the store by providing usage examples.
- Improves the completeness of the integration package.

### Context

- Integration docs: https://kubernetes.io/docs/concepts/configuration/secret
- Example PR of a store doc contribution: #575

**Comment by Ritesh-Udgata** [comment]
I would be happy to contribute so kindly assign this to me.

**Comment by RichardAkman** [comment]
All yours @Ritesh-Udgata
