### ISSUE TITLE
Documentation: `MsSQLConfigStore`

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#595]
### Suggestion

Document the `MsSQLConfigStore` integration with all the necessary details that explain what the store is and how to use it.

### Motivation

- Introduces users to the [ConfigStore](https://docs.configu.com/introduction/concepts#configstore).
- Improves usability of the store by providing usage examples.
- Improves the completeness of the integration package.

### Context

- Integration docs: https://learn.microsoft.com/en-us/sql/sql-server
- Integration SDK docs: https://typeorm.io/data-source-options#mssql-data-source-options
- Example PR of a store doc contribution: #575

**Comment by Ritesh-Udgata** [comment]
Kindly assign me the above issue.
