### ISSUE TITLE
Documentation: `MySQLConfigStore`

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#596]
### Suggestion

Document the `MySQLConfigStore` integration with all the necessary details that explain what the store is and how to use it.

### Motivation

- Introduces users to the [ConfigStore](https://docs.configu.com/introduction/concepts#configstore).
- Improves usability of the store by providing usage examples.
- Improves the completeness of the integration package.

### Context

- Integration docs: https://dev.mysql.com/doc
- Integration SDK docs: https://typeorm.io/data-source-options#mysql--mariadb-data-source-options
- Example PR of a store doc contribution: #575

**Comment by abhirajadhikary06** [comment]
@RichardAkman Can you please assign this to me.

**Comment by RichardAkman** [comment]
All yours! @abhirajadhikary06

**Comment by abhirajadhikary06** [comment]
Thank you 😁. Excited to contribute

**Comment by abhirajadhikary06** [comment]
@RichardAkman please check if I am in the right file path or not ?
![image](https://github.com/user-attachments/assets/7ccf63d9-d148-4b65-9729-b21c23db5721)

**Comment by RichardAkman** [comment]
@abhirajadhikary06, the right file for store docs contribution is the `README.md` file of the integration package. Please take a look at #575 as a reference for what needs to be done.

**Comment by abhirajadhikary06** [comment]
@RichardAkman I have raised a PR. Could you kindly review it, and if everything looks good, please proceed with merging it into the main branch.

**Comment by abhirajadhikary06** [comment]
@RichardAkman I have updated the file with the changes suggested you. Please check it.
