### ISSUE TITLE
Documentation: `SplitConfigStore`

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#597]
### Suggestion

Document the `SplitConfigStore` integration with all the necessary details that explain what the store is and how to use it.

### Motivation

- Introduces users to the [ConfigStore](https://docs.configu.com/introduction/concepts#configstore).
- Improves usability of the store by providing usage examples.
- Improves the completeness of the integration package.

### Context

- Integration docs: https://help.split.io/hc/en-us
- Example PR of a store doc contribution: #575

**Comment by Ritesh-Udgata** [comment]
Got a hang of it . Kindly assign me this as well.

**Comment by RichardAkman** [comment]
All yours @Ritesh-Udgata
