### ISSUE TITLE
Documentation: `TomlFileConfigStore`

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#599]
### Suggestion

Document the `TomlFileConfigStore` integration with all the necessary details that explain what the store is and how to use it.

### Motivation

- Introduces users to the [ConfigStore](https://docs.configu.com/introduction/concepts#configstore).
- Improves usability of the store by providing usage examples.
- Improves the completeness of the integration package.

### Context

- Integration docs: https://toml.io/en/v1.0.0
- Example PR of a store doc contribution: #575

**Comment by PAVAN507-STAR** [comment]
Hii @RichardAkman I would like to work on this issue.Can u please assign this issue to em

**Comment by RichardAkman** [comment]
All yours! @PAVAN507-STAR

**Comment by TomerPacific** [comment]
@RichardAkman - Let me know if I can help with this issue.

**Comment by RichardAkman** [comment]
Hi @PAVAN507-STAR, just checking in since it’s been about a week. Could you let me know if you’re still working on this issue? If not, I’ll go ahead and open it up for other contributors, especially with Hacktoberfest in mind. Thanks for keeping us in the loop!

**Comment by RichardAkman** [comment]
Due to inactivity, we will be making this issue available to other contributors in the spirit of Hacktoberfest.

**Comment by TomerPacific** [comment]
@RichardAkman - Can I help here?

**Comment by RichardAkman** [comment]
Absolutely, all yours @TomerPacific
