### ISSUE TITLE
Implement Python SDK

### ISSUE THREAD

**Issue by RichardAkman** [configu/configu#97]
**Description**

A Python SDK should be created that mirrors the node/ts SDK.

Task overview:
- Only the eval command should be implemented during the first stage.
- Only the Configu store should be implemented during the first stage.

**Motivation**

Expanded functionality for potential users of Configu.

**Comment by RichardAkman** [comment]
@rannn505 Please fill the issue with more details 🙏

**Comment by ShriekinNinja** [comment]
### Strategy and Tasks
first stage will be setting up the project skeleton with all relevant utilities and workflows compliant with PEP8
second stage is implementing @config/ts in python

# Project Setup Tasks
- [ ] Create new branch and merge current draft to it
- [ ] Subscribe to https://pypi.org/
- [ ] Setup poetry for dependencies and publishing
- [ ] Setup testing engine/platform for the project and the types
- [ ] Setup lints/lint-staged for python
- [ ] Create / Edit README for the project - How to install and run the project
- [ ] Update `Python SDK` row in main project README
- [ ] Find most fitting Git Action to build and publish the project

**Comment by dannysheridan** [comment]
@ShriekinNinja @RichardAkman have you thought about auto-generating the Java and Python SDKs? 
buildwithfern.com
